# Workspace setup --------------------------------------------------------------------------
# Check for installed packages and install missing ones
# Packages that will be loaded by this script
packagesToLoad <- c("raster", "rsyncrosim", "dplyr")
# Identify packages that are not already installed
packagesToInstall <- packagesToLoad[!(packagesToLoad %in% installed.packages()[,"Package"])]
# Install missing packages
if(length(packagesToInstall)) install.packages(packagesToInstall)
# Load packages
lapply(packagesToLoad, library, character.only = TRUE)


# Connect to ST-Connect library ------------------------------------------------------------
# Path to package
packagePath <- ssimEnvironment()$PackageDirectory
# Active project
myProject <- project()
# Active scenario
myScenario <- scenario()
# Create temp folder
# Files saved to the results folder will be automatically copied to autogenerated SyncroSim 
# output folders at the end of the simulation
# temp folder must be manually deleted at the end of the simulation (see bottom of this script)
tempFolderPath = envTempFolder("HabitatSuitability")

# Source common R functions for error messaging
source(file.path(packagePath, "common.R"))

# Read in project datasheets
speciesSet <- datasheetExpectData(myProject, "stconnect_Species")

# Read in scenario datasheets
# Input datasheets
runSettings <- datasheetExpectData(myScenario, "stsim_RunControl")
outputOptions <- datasheetExpectData(myScenario, "stconnect_HSOutputOptions")
stateClass = datasheet(myScenario,"stsim_StateClass")
habitatSuitabilityIn = datasheetExpectData(myScenario, "stconnect_HSHabitatSuitability")
habitatPatchIn = datasheetExpectData(myScenario, "stconnect_HSHabitatPatch")

# Output datasheets
habitatSuitabilityOut = datasheet(myScenario, "stconnect_HSOutputHabitatSuitability")
habitatPatchOut = datasheet(myScenario, "stconnect_HSOutputHabitatPatch")


# Manipulate datasheets and prep for simulation --------------------------------------------
# Add state class id values to habitat suitability datasheet to be used when reclassing state class rasters
habitatSuitabilityIn <- habitatSuitabilityIn %>%
    left_join(stateClass, by = c("StateClassID" = "Name"))

# Set of timesteps to analyze
timestepSet <- seq(runSettings$MinimumTimestep, runSettings$MaximumTimestep, by=outputOptions$SpatialOutputHSTimesteps)

# Total iterations
totalIterations <- runSettings$MaximumIteration - runSettings$MinimumIteration + 1
# Total timesteps
totalTimesteps <- runSettings$MaximumTimestep - runSettings$MinimumTimestep + 1


# Run simulation ---------------------------------------------------------------------------
# Report on simulation progress
envBeginSimulation(totalIterations * totalTimesteps)

# Loop over all iterations, timesteps, and species
for (iteration in runSettings$MinimumIteration:runSettings$MaximumIteration) {

    for (timestep in timestepSet) {

        # Report on simulation progress
        envReportProgress(iteration, timestep)

        #Read in state class raster for this iteration and timestep
        stateclassMap <- datasheetRaster(myScenario, datasheet = "stsim_OutputSpatialState", iteration = iteration, timestep = timestep)
        
        for (speciesRow in 1:nrow(speciesSet)) {

            # Species name
            species <- speciesSet[speciesRow, "Name"]
            # Species code
            speciesCode <- speciesSet[speciesRow, "Code"]
            # Species suitability values
            suitabilityValues <- habitatSuitabilityIn %>% 
                filter(SpeciesID == species) %>% 
                select("ID", "Value")
            # Species patch values
            patchValues <- habitatPatchIn %>% 
                filter(SpeciesID == species) %>% 
                select("HabitatSuitabilityThreshold", "MinimumHabitatPatchSize")

            # Check if values exist for this species, if not move to next species 
            if (nrow(suitabilityValues) == 0 || nrow(patchValues) == 0) {
                next
            }

            # Species habitat suitability threshold
            suitabilityThreshold <- patchValues %>% pull(HabitatSuitabilityThreshold)
            
            # Species minimum habitat patch size threshold
            patchSizeThreshold <- patchValues %>% pull(MinimumHabitatPatchSize)

            # Species habitat suitability map
            suitabilityRaster <- reclassify(stateclassMap, rcl = suitabilityValues)

            # Species habitat patch map
            # Create binary map of suitable habitat based on suitability threshold
            # Small patches will be filtered out of this map
            patchRaster <- Which(suitabilityRaster >= suitabilityThreshold)
            
            # Filter out patches below minimum patch size threshold
            # Convert from hectares to m
            conversionFromHa <- res(patchRaster)[1]*res(patchRaster)[2]*(1/10000)
            habitatPatch <- clump(patchRaster)
            habitatPatchID <- data.frame(freq(habitatPatch))
            # Remove clump observations with frequency smaller than minimum patch size threshold (ha)
            habitatPatchID <- habitatPatchID[habitatPatchID$count < patchSizeThreshold/conversionFromHa,]
            habitatPatch[Which(habitatPatch %in% habitatPatchID$value)] <- 0
            # Set NAs from habitat suitability
            habitatPatch[is.na(suitabilityRaster)]<-NA

            # Save rasters to output folder
            # Tag raster names with iteration, timestep, and species code
            suitabilityName <- file.path(tempFolderPath, rasterFileNameSpecies("HabitatSuitability", speciesCode, iteration, timestep, "tif"))
            patchName <- file.path(tempFolderPath, rasterFileNameSpecies("HabitatPatch", speciesCode, iteration, timestep, "tif"))

            # Write habitat suitability raster
            writeRaster(suitabilityRaster, suitabilityName, overwrite = TRUE)
            # Add row to habitatSuitabilityOut datasheet
            newRow <- data.frame(Iteration = iteration, Timestep = timestep, SpeciesID = species, Filename = suitabilityName)
            habitatSuitabilityOut <- addRow(habitatSuitabilityOut, newRow)

            # Write habitat patch raster
            writeRaster(patchRaster, patchName, overwrite = TRUE)
            # Add row to habitatPatchOut datasheet
            newRow <- data.frame(Iteration = iteration, Timestep = timestep, SpeciesID = species, Filename = patchName)
            habitatPatchOut = addRow(habitatPatchOut, newRow)

        } # speciesRow
        # Report on simulation progress
        envStepSimulation()
        
    } # timestep

} # iteration

# Save output data sheets to library -------------------------------------------------------
saveDatasheet(myScenario, habitatSuitabilityOut, "stconnect_HSOutputHabitatSuitability")
saveDatasheet(myScenario, habitatPatchOut, "stconnect_HSOutputHabitatPatch")

# End simulation ---------------------------------------------------------------------------
envEndSimulation()

# This does not work! The temporary HabitatSuitability folder has to be deleted manually
# Deleting it here, removes the temp folder before its contents have been copied to the output folders
# unlink(tempFolderPath, recursive = TRUE)
